version: "3"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-PF-Base.git
    - SERVER_PROFILE_PATH=pingfed
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-internal
      - pingnet-dmz

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-PD-Base.git
    - SERVER_PROFILE_PATH=pingdir

    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8080:8080
      - 8443:8443
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz: