version: "3"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
    # Start with the PF-Base Server Profile
    - SERVER_PROFILE_BASE_URL=https://github.com/cprice-ping/Profile-PF-Base.git
    - SERVER_PROFILE_BASE_PATH=pingfed
    # Add the PF-CIAM Profile to install the PingIDSDK Integration Kit
    - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-PF-CIAM.git
    - SERVER_PROFILE_PATH=pingfed
    - SERVER_PROFILE_PARENT=BASE
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-internal
      - pingnet-dmz

  # Provides the PF-Base API configuration
  pf-config-base:
    image: postman/newman
    command: run https://www.getpostman.com/collections/2e0df14dcf26f1ddb39a -e postman_vars.json --insecure --ignore-redirects
    volumes: 
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./pf_base_vars.json:/etc/newman/postman_vars.json
    networks:
      - pingnet-internal

  # Provides the PF-CIAM API configuration
  pf-config-ciam:
    image: postman/newman
    command: run https://www.getpostman.com/collections/b17a3494b4f4d54de628 -e postman_vars.json --insecure --ignore-redirects
    volumes:
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./pf_ciam_vars.json:/etc/newman/postman_vars.json
    networks:
      - pingnet-internal

  # Configure PA with ACME Managed certificate
  pa-config-proxy:
    image: postman/newman
    command: run https://www.getpostman.com/collections/eaa397bd3a35ef3095c1 -e postman_vars.json --insecure --ignore-redirects
    volumes:
        # An environment file should be injected into the image - this file should contain your specfic info and secrets
        - ./pa_proxy_vars.json:/etc/newman/postman_vars.json

  pingaccess:
    image: pingidentity/pingaccess:edge
    ports:
      - 80:8080
      - 443:3000
    networks: 
      - pingnet-internal
      - pingnet-dmz
  
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8080:8080
      - 8443:8443
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
